server {
  listen 80;
  server_name __APP_DOMAIN__;

  root /var/www/__APP_NAME__/frontend;
  index index.html;

  add_header Permissions-Policy "camera=(self), microphone=(self)" always;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
